language: android
sudo: required
jdk: oraclejdk8
before_cache:
- rm -f $HOME/.gradle/caches/modules-2/modules-2.lock
- rm -fr $HOME/.gradle/caches/*/plugin-resolution/
cache:
  directories:
  - "$HOME/.gradle/caches/"
  - "$HOME/.gradle/wrapper/"
env:
  global:
  - ANDROID_API=27
  - ANDROID_BUILD_TOOLS=27.0.2
  - APK_FINAL_NAME=Blacklist.apk
  - secure: SSPNTIdZBvTK9oWbt9n9XFhEK1mkoYjQkI1GgsfRfvhP3lUmYtyQsSSsGbnN2Ak4TS6HTrLU71Zo2N121Mp5/nfozmd1SbmOPCVofLooUtq7KhLpTnyx3BbDphqRFaXJQ8cTo+D92UOtWS2oSyYwF4KTZ7aeL4lEfU/I7LP/kc/BzDAZ3+fl7D2ah/Y4eSIDpUuOFvWRgFiH5LDlbE4rbf5zlqayhLFCxdJNTGWzb+sqJwQ4yEv4LNBWe+occQPXRUH4PC1plHGrR/73gVH8w5Ik8liWj0gM1qwqlFl2SL1KOfyZCb3buGgSWeBrbogjSVWCyYkEgMKJ9D0xjXptWfxQuREibq+acsGgneIA0uwyNoWmfZKfLJ3dxND6xpUGMfmpzjPHeAHama3PiH1E8Wl9SYf2gY8icjTERlq+lbXciiyvUcZUUAzZwcQDmIC1GmFWNv9vULxOm2fzmjxPIPTYtk3rlq6jTh+BV+iGoHBz3B5CkWp5t1w0UUW+0omsCbA4CgZeQYFsZxjnpm8qeHviwvziIV77JV6q3uYYL3sgFfCsCdftOcCJXyRsp5Aa2Dbm8tKfNZFN9ED8LVEz7Y+gUDjksJYRIrUvPOr5iVVoDFwwfuNWaAy7k+ibN5wxUHltT51yqtD8jeGmPBdtRYHkwqsW8j9caBYYDrVoheQ=
  - secure: Hyy5wfOdSYuz2Z6BoZCUDXYWjstyIETMMpGJj4aRE2hecwi+7y+C4WKOkkicK9Kw30JXkCgP4YCc5w3GlMDLsGJU7EWVWRJdHv4GVZAW5n4vkcAdC0sEJamZT7jg3Xpt2Gv76x9bdGVhi7U0Wuucdh4MzbXZUwStA/uEHU/knUT259YBU/vWqtd0TRGAqakQSOrIgj4fSpBU3gqJdGrDhgOxPO/He5yc9uACN3SPLxXRu361Apz2tSMyJYAAMjd7lOpTlpld5eTXuvnbiQ1guQSuYcw1C09pml3fslAM2z033YFbQT9wq6UDrMuwS+dpDlM2flOqd+udHD7iKQd8+t3cKo7uwMyTY2zYmn39EkGkQgYiOl3+mVxsi4l42Q0A1miMZ65iQ15t4g4ZLlDtS9H+xGqtGBfcGlIayMcIeeCVnjVMJsz7+PXxUkbnb1nPnhiLaQFYixvAVvOpeI5k5hapNpDvYycGBdxwXPOR69FtS+MXwtxlMoKxzArm/dDavVfI0a2/+noOjWmoqa4c4oUhJbqKgC4Vi6k3luk8FMHUzbmf6Xl2J1E+QuRe+JO144YryMMidHJV4pKFmn+vqeaaXD95DcTLM9j6BnGHtVm/qQNjmutPQYgOTe6x2FyBmQhMn/NWfmE3Mdwiwi4yvNVe+Zvyiw5+Kq464CMpInY=
  - secure: hYGWaBOGvySQUJgvS5Bd4kmakUHVvQqGkTuaYpTe+rc8KKSgJkfpFEzrm9elcWaW9bCqnQet3m4HdL0fp1SUrC9uXQCDDNn4B8urfiRZKrmniykIuL65uvN80NcvMud3K8vIKpEy4cCHjl44qY/WCTBVAIjjJSLan6wfbWXfBvSM6G938gJFmHbR5FicjoBRJbq8wF+Vz9LXISLBgHkWHrvQrDh+33coca5xEA39e8VxDjg+w9akBjuWKh4LP0FDrGMaVIScL7cCvkKyyWRCaqPTaRdvM66FmNoSomuPP1JMMS6S4PJEfVe9ZvU2MkWN5qjFZhvsX7SbvWY4zq6S4it0El0VU3bHmzohf3TjMvcBdUAFUsaf1sw/9IW5s87QkMbgJ415VKpMrJR1wHrhQt6xF1PG+n//37j/pEiNew0zjeYYXyhG0lO8MorHDDaqiffJzHO9s9xt+37gtxvg93YLkahvGfyRG6n85pw3cMbp8e+AMKbK4w9CLX88mBWLv3Uv4ZWDS4zS9gLTNWV1e+heYVk9gdWqm1znfwIyiDXK4fwGwrjI43NhVVHUFyg4klB90RruxkMCd3+x1kJe3hbR1325FE1VRoSqKGGKYpQgtqjN5MZn5EK6srrmCZprp+QpZ4sL8sftTPGFtfENbzHg7GDnEIssBFrIWitkkZw=
  - secure: Dpi8sCgOIftwfLP5TIb/5Xw1kCqwAz12j1HHYsFEFPET2Z1pYRoyaPZGQSXtCtrCBcoHstp/lgYTjTJB7Wo66CrnMMOFWGf/TO2Zx6BDfACklHOwAarvBPHxKb3sigYWMpkLtXjPAoykOU++hfx8H6dwjFyn8neztn82VwVKXcl9Y2ecHXzzibqPufItrqsknOlDy4u74sJDiyiH9/fA8grHVSJ5LvDj4m+2ROzxDdlD5wqFHX8fqrcPnZPMg0XwzYBFikn54JegyH/jF7ge8HoUVo+R0xzhNzRdbJH8xj1M7xXXRtS0TbuNVdFDBVg8ay9U+B7vgW+8WAEI1TsVKoauPWedfyvEkmg6gPN7AEIvvblWbHYevpLmcOJU0q/CGJs+/2Rmm6DXSGlNG0pjl8EtlH3n6XGhI9en5lIEWq3v3s2EIZcco6N66OCLoIO4mLUbWaVxplZAyD8TLqzDvySiMGt3E6kiS3K9WFsf7iD5ngeuPthFf9lIy7csEbAjAKgVBHoRD2nE16gotPg9cYoXbbTq62Rp4bSPxfpelOZqkyT8eDCCVIbu+cxmETehojo9yHmDqq8YI2hNKZeVl6SktOrQMGFGI3FxHqE0gH9UxED4mpWBIR66weaMuOMzAnFsFT2Ip5Dl/2Hb5sZU7Uibb9BEjXSiksSZybxE5IA=
  - secure: JaN0w6Xc4vt4h+qxPgb1MLCLUS9e8IdhYtBbnqoWK03GIw0owLQ3tU1zOSkH2yysMQ91wwLddNqTON5DLfHe+U6VUDNEkMJUBi4HJBO0LjcbY0QwnXS+j7ACfIngVQ4OPL+Y8R2nmlunTEIaSyMDBK7w6fJxxIobz5LsYLm8OiZy7jBlIIsvQB+mshn160gi1CWFvrz8f/PbidHZXf+nPjtSvsSafxNqHqKqNMPJtyZ+xt8CiCrR3H7PThkvsy61QIfqKCZntFyaDtRSmstEXGalq3HnFmtqAMkGLh+eYG4K3hoEq5Aslw8zkVg52QhBohef4W7f8OvY+7N3fHJLbEMvjxcrmVK8vpgO1IhruNe9oymSsSB6cmir7dT+QMLh9m9OXSta+tbci71fzfa+C4kTsZutNtucngKyjxYNZRYUQMUovYcNHJD45phvJ88R9haT/RCbE/BNvRlDp+fRBwBlXWu7qcfB9Opg9wlZZwn07eFgqyccxLRuCW2OwUTYZP0RR1h4a89lz8FvzdLtmHyYBhFREtVLAzpY6DNwS0HM3rTghI0dsUNs9EMqzRi2h+44SKL5Nvp2ITI22dAX9E77WAG9UeEBllB+Oclba9p5kzYLHbedDj2wAnr5waonXZhKdCywGaPnzeM2m9071Zq/OPxbIQs+8MtMuMy1jQA=
android:
  components:
  - tools
  - platform-tools
  - tools
  - build-tools-$ANDROID_BUILD_TOOLS
  - android-$ANDROID_API
  - extra-android-support
  - extra-google-m2repository
  - extra-android-m2repository
before_install:
- openssl aes-256-cbc -k "$travisKeystoreEncPassword" -in travis.keystore.enc -out
  travis.keystore -d
- cd app
- openssl aes-256-cbc -k "$fabricPropertiesEncPassword" -in fabric.properties.enc
  -out fabric.properties -d
- cd ..
- chmod +x gradlew
script:
- "./gradlew clean build test --stacktrace"
before_deploy:
- cp $TRAVIS_BUILD_DIR/travis.keystore $HOME
- cd app/build/outputs/apk/release
- "${ANDROID_HOME}/build-tools/${ANDROID_BUILD_TOOLS}/zipalign -v 4 app-release-unsigned.apk app-release-unsigned-aligned.apk"
- "${ANDROID_HOME}/build-tools/${ANDROID_BUILD_TOOLS}/apksigner sign --ks $HOME/travis.keystore --ks-key-alias ${keyAlias} --ks-pass pass:${storePassword} --key-pass pass:${keyPassword} --out ${APK_FINAL_NAME} app-release-unsigned-aligned.apk"
- "${ANDROID_HOME}/build-tools/${ANDROID_BUILD_TOOLS}/apksigner verify ${APK_FINAL_NAME}"
- git config --global user.email "travis@travis-ci.org"
- git config --global user.name "Travis"
- git tag -a v2.0 -m "Travis build 2.0 pushed a tag."
- git push origin --tags
- git fetch origin

deploy:
  provider: releases
  file: $APK_FINAL_NAME
  skip_cleanup: true
  on:
    branch: master
    repo: TofiBashers/Blacklist
    jdk: oraclejdk8
  api_key:
    secure: BSoStinYJ48C1xYvvJXh8VYa2ZetIMAtLgDGljmOrwwPZ5oEBKuqq5w51Xy/BtPkn9iQG6SuxXzyShkuCVvouYdZopOJatE5cLTzT9fXWp7200NL9sXBdyhPFdugqJvNOqcXUNQ29g70lC11WU1OCXzBpRtu9pl84zwgLD4i8njfVwHDLlzrzdUhGRJWXrpybGO3tf4U5zoG2bmATuYT1H2BklU56rSR7kstwZ5bSaJXwIcF0vPYBAIOiaaoW4w3OVYZRvtBOvLCekSlDM49Mey5peesWHJiI5aEU12BMNVevcKWBwrlj9w9z9SJIAQPRzerBYlfZKPerBTi2QYqDHWWvANmLbGze1xo9S6D3kASHjohoyu2TcOgcbtVeYpTEyOT5+jECbl84Dlk/fH14JtT291V1SYPPSPEKM3PMn/cOcVtN/FDJsqBNzX9xY+AbvNIlcMORv+aJhlyA8cQ2nGTyl4RkKRkwukemNW3rVFjGjc5NhsIVDHUkgeTRYDVutXfq/DdFmiSQRfesSHaZDkhaqjry/kRCVPN/ol4rzRwNH0mlBQGtBz07yuoqJs4TYPf3joUZ0EBs6zEhkMsmMeN/hDDWLogfqLD+OfhvZP3AZixVHBjkeDS7uI1TJytOb2pwCkbOdujdLf4ZA8/BxQ+A7G/XJtWaFjrwcFHzvI=
