package com.gmail.tofibashers.blacklist.utils


/**
 * Created by TofiBashers on 25.01.2018.
 */
object AndroidComponentKeys {

    const val TAG_TIMEPICKER_DIALOG = "TAG_TIMEPICKER_DIALOG"
    const val TAG_SAVED_NUMBER_ALREADY_EXISTS_DIALOGFRAGMENT = "TAG_SAVED_NUMBER_ALREADY_EXISTS_DIALOGFRAGMENT"
    const val BUNDLE_ON_TIME_CHANGE_VIEW_POSITION = "BUNDLE_ON_TIME_CHANGE_VIEW_POSITION"
    const val BUNDLE_TIME_CHANGE_IS_BEGIN = "BUNDLE_TIME_CHANGE_IS_BEGIN"
    const val EXTRA_ADDRESS = "address"
    const val TYPE_MMS_SMS = "vnd.android-dir/mms-sms"

    const val REQUEST_CODE_PHONENUMBER_OPTIONS_VIEW = 1
    const val REQUEST_CODE_BLACKLIST_CONTACT_OPTIONS_VIEW = 2
    const val REQUEST_CODE_TIME_SETTINGS_VIEW = 3
    const val REQUEST_CODE_SELECT_CONTACT_VIEW = 4
}